version: '3.8'

services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: profil_first_api
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - uploads:/app/src/uploads
      - profil_first_data:/data/db
    networks:
      - profil_first_network
    restart: always

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - profil_first_network
    restart: always

volumes:
  uploads:
  profil_first_data:

networks:
  profil_first_network:
    driver: bridge
